pgdefault: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: wolf_development
  username: rails
  password: dbadminpass

test:
  <<: *default
  database: wolf_test
  username: rails
  password: dbadminpass

production:
  <<: *default
  database: wolf_production
  username: rails
  password: <%= ENV["DATABASE_RAILS_PASSWORD"] %>
